version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8000:8000"  # Map your app's port to the host
    depends_on:
      - redis
      - qdrant
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    command: >
      sh -c "pdm install && pdm run python app/main.py"  # Install dependencies and run the app

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Map Redis port to the host
    volumes:
      - redis_data:/data  # Optional: Persist Redis data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_container
    ports:
      - "6333:6333"  # Map Qdrant port to the host
      - "6334:6334"  # Optional: Internal Qdrant port
    volumes:
      - qdrant_data:/qdrant/storage  # Persist Qdrant data

volumes:
  redis_data:
  qdrant_data:
